apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
{{#if gcp}}        
  accessPolicy:
    outbound:
      rules:
        - application: {{uttak}}
      external:
        - host: {{appres}}
{{/if}}               
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /health/isAlive
      initialDelay: 60
  readiness:
      path: /health/isReady
      initialDelay: 60  
  prometheus:
      enabled: false
      path: /internal/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env: 
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
   - name: APP_VERSION
     value: {{image}}
  webproxy: true
