packages:
  - apps/*
  - packages/*
  - server
  - server-uinnlogget

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@navikt/*'
  - vite@8.0.5

onlyBuiltDependencies:
  - msw
