packages:
  - apps/*
  - packages/*
  - server
  - server-uinnlogget

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@navikt/*'
  - vite@8.0.5

onlyBuiltDependencies:
  - msw

overrides:
  js-cookie: 3.0.7
patchedDependencies:
  react-hook-form@7.79.0: patches/react-hook-form@7.79.0.patch
