export enum OversiktRoutes {
    HOVEDSIDE = '/',
    SAKSOVERSIKT = '/sak',
    DIN_PLAN = 'din-plan',
    DOKUMENTER = 'dokumenter',
    ETTERSEND = 'ettersend',
    INNTEKTSMELDING = 'inntektsmelding',
    TIDSLINJEN = 'tidslinjen',
    OPPGAVER = 'oppgaver',
    BRUKT_OPPLYSNINGER_OM_ARBEIDSFORHOLD = 'brukt-opplysninger-om-arbeidsforhold',
}

export enum NavRoutes {
    SAKSBEHANDLINGSTIDER = 'https://www.nav.no/saksbehandlingstider',
    SAKSBEHANDLINGSTIDER_FP = 'https://www.nav.no/saksbehandlingstider#foreldrepenger',
    SAKSBEHANDLINGSTIDER_SVP = 'https://www.nav.no/saksbehandlingstider#svangerskapspenger',
    SAKSBEHANDLINGSTIDER_ES = 'https://www.nav.no/saksbehandlingstider#engangsstonad',
    KLAGERETTIGHETER = 'https://www.nav.no/klage',
    KLAGERETTIGHETER_FP = 'https://www.nav.no/klage#foreldrepenger',
    KLAGERETTIGHETER_SVP = 'https://www.nav.no/klage#svangerskapspenger',
    KLAGERETTIGHETER_ES = 'https://www.nav.no/klage#engangsstonad',
    CHAT_MED_OSS = 'https://www.nav.no/person/kontakt-oss/chat/familie',
    SKRIV_TIL_OSS = 'https://innboks.nav.no/s/skriv-til-oss?category=Familie',
    RING_OSS = 'tel:55553333',
    SE_FLERE_TLF_NR_OG_TASTEVALG = 'https://www.nav.no/kontaktoss#ring-oss',
    LES_MER_OM_VÅRE_PENGESTØTTER = 'https://www.nav.no/barn',
    LES_MER_OM_FORELDREPENGER = 'https://www.nav.no/foreldrepenger',
    LES_MER_OM_SVANGERSKAPSPENGER = 'https://familie.nav.no/om-svangerskapspenger',
    LES_MER_OM_ENGANGSTØNAD = 'https://familie.nav.no/om-engangsstonad',
    MELD_FRA_OM_ENDRINGER = 'https://www.nav.no/foreldrepenger#melde',
    VENT_INNTEKTSMELDING = 'https://www.nav.no/arbeidsgiver/inntektsmelding',
    VENT_MELDEKORT = 'https://www.nav.no/no/person/arbeid/dagpenger-ved-arbeidsloshet-og-permittering/meldekort-hvordan-gjor-du-det',
    SØKNADSFRISTER = 'https://www.nav.no/foreldrepenger#for-soknad',
    FORELDREPENGESOKNAD = 'https://foreldrepengesoknad.nav.no',
    HVOR_LENGE = 'https://www.nav.no/foreldrepenger#hvor-lenge',
}
