export enum BehandlingTilstand {
    TIDLIG_SØKNAD = 'TIDLIG_SØKNAD',
    VENTER_PÅ_INNTEKTSMELDING = 'VENTER_PÅ_INNTEKTSMELDING',
    VENTER_PÅ_DOKUMENTASJON = 'VENTER_PÅ_DOKUMENTASJON',
    UNDER_BEHANDLING = 'UNDER_BEHANDLING',
}
