FROM europe-north1-docker.pkg.dev/nais-management-233d/teamforeldrepenger/navikt/foreldrepengesoknad/server:latest
LABEL org.opencontainers.image.source=https://github.com/navikt/foreldrepengesoknad/tree/master/apps/foreldrepengeoversikt
COPY ./dist ./dist/
