const MAKS_PERMISJONSLENGDE_I_ÅR = 3;
const MAKS_FERIEDAGER_ETT_ÅR = 21;
const MAKS_FERIEDAGER_MED_OVERFØRING = 52;
const ANTALL_UKER_MØDREKVOTE_ETTER_FØDSEL = 6;
const ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL = 3;
const MAKS_ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL = 12;

const uttaksConstants = {
    MAKS_PERMISJONSLENGDE_I_ÅR,
    MAKS_FERIEDAGER_ETT_ÅR,
    MAKS_FERIEDAGER_MED_OVERFØRING,
    ANTALL_UKER_MØDREKVOTE_ETTER_FØDSEL,
    ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL,
    MAKS_ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL,
};

export default uttaksConstants;
