// This file is auto-generated by @hey-api/openapi-ts

export type KontoBeregningDto = {
    kontoer: KontoDto[];
    minsteretter: Minsteretter;
    tillegg?: Tillegg;
};

export type KontoDto = {
    dager: number;
    konto: KontoTypeUttak;
};

export type KontoTypeUttak =
    | 'MØDREKVOTE'
    | 'FEDREKVOTE'
    | 'FELLESPERIODE'
    | 'FORELDREPENGER'
    | 'FORELDREPENGER_FØR_FØDSEL'
    | 'AKTIVITETSFRI_KVOTE';

export type Minsteretter = {
    farRundtFødsel: number;
    toTette: number;
};

export type Tillegg = {
    flerbarn: number;
    prematur: number;
};

export type KontoBeregningResultatDto = {
    80: KontoBeregningDto;
    100: KontoBeregningDto;
};

export type KontoBeregningGrunnlagDto = {
    antallBarn: number;
    brukerrolle: no_nav_foreldrepenger_stønadskonto_regelmodell_grunnlag_Brukerrolle;
    familieHendelseDatoNesteSak?: string;
    fødselsdato?: string;
    morHarUføretrygd?: boolean;
    omsorgsovertakelseDato?: string;
    rettighetstype: no_nav_foreldrepenger_stønadskonto_regelmodell_grunnlag_Rettighetstype;
    termindato?: string;
};

export type no_nav_foreldrepenger_stønadskonto_regelmodell_grunnlag_Brukerrolle = 'MOR' | 'FAR' | 'MEDMOR' | 'UKJENT';

export type no_nav_foreldrepenger_stønadskonto_regelmodell_grunnlag_Rettighetstype =
    | 'ALENEOMSORG'
    | 'BARE_SØKER_RETT'
    | 'BEGGE_RETT';
