// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type EksternArbeidsforholdDto_fpoversikt = {
    arbeidsgiverId: string;
    arbeidsgiverIdType: string;
    arbeidsgiverNavn: string;
    from: string;
    stillingsprosent: number;
    to?: string;
};

export type MorArbeidRequest_fpoversikt = {
    annenPartFødselsnummer: string;
    barnFødselsnummer?: string;
    familiehendelse?: string;
    perioder?: PeriodeRequest_fpoversikt[];
};

export type PeriodeRequest_fpoversikt = {
    fom: string;
    periodeType?: PeriodeMedAktivitetskravType_fpoversikt;
    tom: string;
};

export type PeriodeMedAktivitetskravType_fpoversikt = 'UTTAK' | 'UTSETTELSE';

export type DokumentDto_fpoversikt = {
    dokumentId?: string;
    journalpostId?: string;
    mottatt: string;
    saksnummer?: string;
    tittel?: string;
    type: JournalpostType_fpoversikt;
};

export type JournalpostType_fpoversikt = 'INNGÅENDE_DOKUMENT' | 'UTGÅENDE_DOKUMENT';

export type ProsessTaskDataDto_fpoversikt = {
    gruppe: string;
    id: number;
    nesteKjøringEtter?: string;
    sekvens: string;
    sistKjørt?: string;
    sisteFeilKode?: string;
    status: string;
    taskParametre?: {
        [key: string]: string;
    };
    taskType: string;
};

export type ProsessTaskOpprettInputDto_fpoversikt = {
    taskParametre: {
        [key: string]: string;
    };
    taskType: string;
};

export type FeiletProsessTaskDataDto_fpoversikt = {
    feiledeForsøk?: number;
    gruppe: string;
    id: number;
    nesteKjøringEtter?: string;
    sekvens: string;
    sistKjørt?: string;
    sisteFeilKode?: string;
    status: string;
    taskParametre?: {
        [key: string]: string;
    };
    taskType: string;
    sisteFeilTekst?: string;
    sisteKjøringServerProsess?: string;
};

export type IkkeFerdigProsessTaskStatusEnum_fpoversikt = 'FEILET' | 'VENTER_SVAR' | 'SUSPENDERT' | 'VETO' | 'KLAR';

/**
 * Resultatet av asynkron-restart av en eksisterende prosesstask
 */
export type ProsessTaskRestartResultatDto_fpoversikt = {
    /**
     * Kjøretidspunkt for restart av prosessen
     */
    nesteKjoeretidspunkt: string;
    prosessTaskId: number;
    /**
     * Nåværende status (KLAR)
     */
    prosessTaskStatus: string;
};

export type FeiletProsessTaskStatusEnum_fpoversikt = 'FEILET' | 'VENTER_SVAR' | 'SUSPENDERT';

/**
 * Resultatet av asynkron-restart av feilede prosesstasks
 */
export type ProsessTaskRetryAllResultatDto_fpoversikt = {
    /**
     * Prosesstasks som restartes
     */
    prosessTaskIds?: number[];
};

export type SokeFilterDto_fpoversikt = {
    sisteKjoeretidspunktFraOgMed?: string;
    sisteKjoeretidspunktTilOgMed?: string;
    tekst: string;
};

export type BortfaltNaturalytelse_fpoversikt = {
    beløpPerMnd?: number;
    fomDato?: string;
    tomDato?: string;
    type?: NaturalytelseType_fpoversikt;
};

export type FpOversiktInntektsmeldingDto_fpoversikt = {
    arbeidsgiverIdent?: string;
    arbeidsgiverNavn?: string;
    bortfalteNaturalytelser?: BortfaltNaturalytelse_fpoversikt[];
    erAktiv?: boolean;
    inntektPrMnd?: number;
    journalpostId?: string;
    mottattTidspunkt?: string;
    refusjonPrMnd?: number;
    refusjonsperioder?: Refusjon_fpoversikt[];
    startDatoPermisjon?: string;
    stillingsprosent?: number;
    versjon?: number;
};

export type NaturalytelseType_fpoversikt =
    | 'ELEKTRISK_KOMMUNIKASJON'
    | 'AKSJER_GRUNNFONDSBEVIS_TIL_UNDERKURS'
    | 'LOSJI'
    | 'KOST_DØGN'
    | 'BESØKSREISER_HJEMMET_ANNET'
    | 'KOSTBESPARELSE_I_HJEMMET'
    | 'RENTEFORDEL_LÅN'
    | 'BIL'
    | 'KOST_DAGER'
    | 'BOLIG'
    | 'SKATTEPLIKTIG_DEL_FORSIKRINGER'
    | 'FRI_TRANSPORT'
    | 'OPSJONER'
    | 'TILSKUDD_BARNEHAGEPLASS'
    | 'ANNET'
    | 'BEDRIFTSBARNEHAGEPLASS'
    | 'YRKEBIL_TJENESTLIGBEHOV_KILOMETER'
    | 'YRKEBIL_TJENESTLIGBEHOV_LISTEPRIS'
    | 'INNBETALING_TIL_UTENLANDSK_PENSJONSORDNING';

export type Refusjon_fpoversikt = {
    fomDato?: string;
    refusjonsbeløpMnd?: number;
};

export type DokumentType_fpoversikt =
    | 'I000001'
    | 'I000002'
    | 'I000003'
    | 'I000004'
    | 'I000005'
    | 'I000006'
    | 'I000050'
    | 'I000027'
    | 'I500027'
    | 'I000114'
    | 'I000119'
    | 'I000067'
    | 'I000007'
    | 'I000023'
    | 'I000026'
    | 'I000032'
    | 'I000036'
    | 'I000037'
    | 'I000038'
    | 'I000039'
    | 'I000041'
    | 'I000042'
    | 'I000043'
    | 'I000044'
    | 'I000045'
    | 'I000047'
    | 'I000049'
    | 'I000051'
    | 'I000060'
    | 'I000061'
    | 'I000062'
    | 'I000063'
    | 'I000064'
    | 'I000065'
    | 'I000066'
    | 'I000107'
    | 'I000108'
    | 'I000109'
    | 'I000110'
    | 'I000111'
    | 'I000112'
    | 'I000116'
    | 'I000117'
    | 'I000118'
    | 'I000120'
    | 'I000121'
    | 'I000122'
    | 'I000123'
    | 'I000124'
    | 'I000130'
    | 'I000131'
    | 'I000132'
    | 'I000133'
    | 'I000140'
    | 'I000141'
    | 'I000143'
    | 'I000144'
    | 'I000145'
    | 'I000146'
    | 'I500001'
    | 'I500002'
    | 'I500003'
    | 'I500004'
    | 'I500005'
    | 'I500006'
    | 'I500050';

export type TilbakekrevingUttalelseOppgave_fpoversikt = {
    frist?: string;
    opprettet: string;
    saksnummer: string;
};

export type Navn_fpoversikt = {
    fornavn: string;
    mellomnavn?: string;
    etternavn: string;
};

export type Bankkonto_fpoversikt = {
    banknavn?: string;
    kontonummer?: string;
};

export type Kjønn_fpoversikt = 'M' | 'K' | 'U';

export type Sivilstand_fpoversikt = {
    type?: SivilstandType_fpoversikt;
};

export type SivilstandType_fpoversikt =
    | 'UOPPGITT'
    | 'UGIFT'
    | 'GIFT'
    | 'ENKE_ELLER_ENKEMANN'
    | 'SKILT'
    | 'SEPARERT'
    | 'REGISTRERT_PARTNER'
    | 'SEPARERT_PARTNER'
    | 'SKILT_PARTNER'
    | 'GJENLEVENDE_PARTNER';

export type Målform_fpoversikt = 'NB' | 'NN' | 'EN' | 'E';

export type PersonDto_fpoversikt = {
    aktørid?: string;
    bankkonto?: Bankkonto_fpoversikt;
    barn: BarnDto_fpoversikt[];
    fnr: string;
    fødselsdato: string;
    kjønn: Kjønn_fpoversikt;
    målform?: Målform_fpoversikt;
    navn: Navn_fpoversikt;
    sivilstand?: Sivilstand_fpoversikt;
};

export type AnnenForelderDto_fpoversikt = {
    fnr: string;
    fødselsdato?: string;
    navn: Navn_fpoversikt;
};

export type BarnDto_fpoversikt = {
    annenPart?: AnnenForelderDto_fpoversikt;
    dødsdato?: string;
    fnr: string;
    fødselsdato: string;
    kjønn: Kjønn_fpoversikt;
    navn: Navn_fpoversikt;
};

export type PersonMedArbeidsforholdDto_fpoversikt = {
    arbeidsforhold: EksternArbeidsforholdDto_fpoversikt[];
    person: PersonDto_fpoversikt;
};

export type AnnenPartRequest_fpoversikt = {
    annenPartFødselsnummer: string;
    barnFødselsnummer?: string;
    familiehendelse?: string;
};

export type Aktivitet_fpoversikt = {
    arbeidsgiver?: Arbeidsgiver_fpoversikt;
    arbeidsgiverNavn?: string;
    type: AktivitetType_fpoversikt;
};

export type AktivitetType_fpoversikt = 'FRILANS' | 'ORDINÆRT_ARBEID' | 'SELVSTENDIG_NÆRINGSDRIVENDE' | 'ANNET';

export type AnnenPartSak_fpoversikt = {
    antallBarn: number;
    dekningsgrad: DekningsgradSak_fpoversikt;
    perioder: UttakPeriode_fpoversikt[];
    termindato?: string;
};

export type Arbeidsgiver_fpoversikt = {
    id: string;
    type?: ArbeidsgiverType_fpoversikt;
};

export type ArbeidsgiverType_fpoversikt = 'PRIVAT' | 'ORGANISASJON';

export type BrukerRolleSak_fpoversikt = 'MOR' | 'FAR_MEDMOR';

export type DekningsgradSak_fpoversikt = 'ÅTTI' | 'HUNDRE';

export type Gradering_fpoversikt = {
    aktivitet: Aktivitet_fpoversikt;
    arbeidstidprosent: number;
};

export type KontoType_fpoversikt =
    | 'MØDREKVOTE'
    | 'FEDREKVOTE'
    | 'FELLESPERIODE'
    | 'FORELDREPENGER'
    | 'FORELDREPENGER_FØR_FØDSEL';

export type MorsAktivitet_fpoversikt =
    | 'ARBEID'
    | 'UTDANNING'
    | 'KVALPROG'
    | 'INTROPROG'
    | 'TRENGER_HJELP'
    | 'INNLAGT'
    | 'ARBEID_OG_UTDANNING'
    | 'UFØRE'
    | 'IKKE_OPPGITT';

export type UttakOppholdÅrsak_fpoversikt =
    | 'MØDREKVOTE_ANNEN_FORELDER'
    | 'FEDREKVOTE_ANNEN_FORELDER'
    | 'FELLESPERIODE_ANNEN_FORELDER'
    | 'FORELDREPENGER_ANNEN_FORELDER';

export type UttakOverføringÅrsak_fpoversikt =
    | 'INSTITUSJONSOPPHOLD_ANNEN_FORELDER'
    | 'SYKDOM_ANNEN_FORELDER'
    | 'IKKE_RETT_ANNEN_FORELDER'
    | 'ALENEOMSORG';

export type UttakPeriode_fpoversikt = {
    flerbarnsdager?: boolean;
    fom: string;
    forelder?: BrukerRolleSak_fpoversikt;
    gradering?: Gradering_fpoversikt;
    kontoType?: KontoType_fpoversikt;
    morsAktivitet?: MorsAktivitet_fpoversikt;
    oppholdÅrsak?: UttakOppholdÅrsak_fpoversikt;
    overføringÅrsak?: UttakOverføringÅrsak_fpoversikt;
    resultat?: UttakPeriodeResultat_fpoversikt;
    samtidigUttak?: number;
    tom: string;
    utsettelseÅrsak?: UttakUtsettelseÅrsak_fpoversikt;
};

export type UttakPeriodeResultat_fpoversikt = {
    innvilget?: boolean;
    trekkerDager?: boolean;
    trekkerMinsterett?: boolean;
    årsak?: UttakPeriodeResultatÅrsak_fpoversikt;
};

export type UttakPeriodeResultatÅrsak_fpoversikt =
    | 'ANNET'
    | 'AVSLAG_HULL_MELLOM_FORELDRENES_PERIODER'
    | 'AVSLAG_FRATREKK_PLEIEPENGER'
    | 'AVSLAG_UTSETTELSE_TILBAKE_I_TID'
    | 'INNVILGET_UTTAK_AVSLÅTT_GRADERING_TILBAKE_I_TID';

export type UttakUtsettelseÅrsak_fpoversikt =
    | 'HV_ØVELSE'
    | 'ARBEID'
    | 'LOVBESTEMT_FERIE'
    | 'SØKER_SYKDOM'
    | 'SØKER_INNLAGT'
    | 'BARN_INNLAGT'
    | 'NAV_TILTAK'
    | 'FRI';

export type BehandlingTilstand_fpoversikt =
    | 'UNDER_BEHANDLING'
    | 'VENT_TIDLIG_SØKNAD'
    | 'VENT_MELDEKORT'
    | 'VENT_DOKUMENTASJON'
    | 'VENT_INNTEKTSMELDING'
    | 'PROSESSERER';

export type EsSak_fpoversikt = {
    familiehendelse: Familiehendelse_fpoversikt;
    gjelderAdopsjon?: boolean;
    oppdatertTidspunkt: string;
    sakAvsluttet?: boolean;
    saksnummer: string;
    åpenBehandling?: EsÅpenBehandling_fpoversikt;
};

export type EsÅpenBehandling_fpoversikt = {
    tilstand: BehandlingTilstand_fpoversikt;
};

export type Familiehendelse_fpoversikt = {
    antallBarn: number;
    fødselsdato?: string;
    omsorgsovertakelse?: string;
    termindato?: string;
};

export type FpSak_fpoversikt = {
    annenPart?: Person_fpoversikt;
    barn?: Person_fpoversikt[];
    dekningsgrad?: DekningsgradSak_fpoversikt;
    familiehendelse: Familiehendelse_fpoversikt;
    forelder: BrukerRolleSak_fpoversikt;
    gjeldendeVedtak?: FpVedtak_fpoversikt;
    gjelderAdopsjon: boolean;
    harAnnenForelderTilsvarendeRettEØS?: boolean;
    kanSøkeOmEndring: boolean;
    morUføretrygd: boolean;
    oppdatertTidspunkt: string;
    rettighetType: RettighetType_fpoversikt;
    sakAvsluttet: boolean;
    sakTilhørerMor: boolean;
    saksnummer: string;
    åpenBehandling?: FpÅpenBehandling_fpoversikt;
    ønskerJustertUttakVedFødsel?: boolean;
};

export type FpVedtak_fpoversikt = {
    perioder: UttakPeriode_fpoversikt[];
    perioderAnnenpartEøs?: UttakPeriodeAnnenpartEøs_fpoversikt[];
};

export type FpÅpenBehandling_fpoversikt = {
    søknadsperioder: UttakPeriode_fpoversikt[];
    tilstand: BehandlingTilstand_fpoversikt;
};

export type Person_fpoversikt = {
    aktørId?: string;
    fnr?: string;
};

export type RettighetType_fpoversikt = 'ALENEOMSORG' | 'BEGGE_RETT' | 'BARE_SØKER_RETT';

export type Saker_fpoversikt = {
    engangsstønad: EsSak_fpoversikt[];
    foreldrepenger: FpSak_fpoversikt[];
    svangerskapspenger: SvpSak_fpoversikt[];
};

export type UttakPeriodeAnnenpartEøs_fpoversikt = {
    fom: string;
    kontoType: KontoType_fpoversikt;
    tom: string;
    trekkdager: number;
    trekkonto: KontoType_fpoversikt;
};

export type AvslutningÅrsak_fpoversikt =
    | 'NORMAL'
    | 'TILBAKE_I_HEL_STILLING'
    | 'AVSLAG_OVERGANG_FORELDREPENGER'
    | 'AVSLAG_FØDSEL'
    | 'AVSLAG_TIDSPERIODE_FØR_TERMIN'
    | 'AVSLAG_ANNET'
    | 'AVSLAG_INNGANGSVILKÅR';

export type OppholdPeriode_fpoversikt = {
    fom: string;
    oppholdKilde: OppholdKilde_fpoversikt;
    tom: string;
    årsak: OppholdÅrsak_fpoversikt;
};

export type OppholdKilde_fpoversikt = 'SAKSBEHANDLER' | 'INNTEKTSMELDING' | 'SØKNAD';

export type OppholdÅrsak_fpoversikt = 'SYKEPENGER' | 'FERIE';

export type PeriodeResultat_fpoversikt = {
    resultatType?: ResultatType_fpoversikt;
    utbetalingsgrad?: number;
};

export type ResultatType_fpoversikt = 'INNVILGET' | 'AVSLAG_SØKNADSFRIST' | 'AVSLAG_ANNET';

export type SvpArbeidsforhold_fpoversikt = {
    aktivitet: Aktivitet_fpoversikt;
    avslutningÅrsak?: AvslutningÅrsak_fpoversikt;
    behovFrom?: string;
    oppholdsperioder: OppholdPeriode_fpoversikt[];
    risikofaktorer?: string;
    tilrettelegginger: Tilrettelegging_fpoversikt[];
    tiltak?: string;
};

export type ForsendelseStatus = {
    status: 'PENDING' | 'MIDLERTIDIG' | 'ENDELIG';
    saksnummer?: number;
};

export type SvpSak_fpoversikt = {
    familiehendelse: Familiehendelse_fpoversikt;
    gjeldendeVedtak?: Vedtak_fpoversikt;
    oppdatertTidspunkt: string;
    sakAvsluttet: boolean;
    saksnummer: string;
    åpenBehandling?: SvpÅpenBehandling_fpoversikt;
};

export type SvpÅpenBehandling_fpoversikt = {
    søknad: Søknad_fpoversikt;
    tilstand: BehandlingTilstand_fpoversikt;
};

export type Søknad_fpoversikt = {
    arbeidsforhold: SvpArbeidsforhold_fpoversikt[];
};

export type Tilrettelegging_fpoversikt = {
    arbeidstidprosent?: number;
    fom: string;
    resultat?: PeriodeResultat_fpoversikt;
    tom: string;
    type?: TilretteleggingType_fpoversikt;
};

export type TilretteleggingType_fpoversikt = 'HEL' | 'DELVIS' | 'INGEN';

export type Vedtak_fpoversikt = {
    arbeidsforhold: SvpArbeidsforhold_fpoversikt[];
    avslagÅrsak?: AvslagÅrsak_fpoversikt;
};

export type AvslagÅrsak_fpoversikt =
    | 'ARBEIDSGIVER_KAN_TILRETTELEGGE'
    | 'SØKER_ER_INNVILGET_SYKEPENGER'
    | 'MANGLENDE_DOKUMENTASJON'
    | 'ANNET';

export type TidslinjeHendelseDto_fpoversikt = {
    aktørType: AktørType_fpoversikt;
    dokumenter: Dokument_fpoversikt[];
    opprettet: string;
    tidslinjeHendelseType: TidslinjeHendelseType_fpoversikt;
};

export type AktørType_fpoversikt = 'BRUKER' | 'NAV' | 'ARBEIDSGIVER';

export type Dokument_fpoversikt = {
    dokumentId?: string;
    journalpostId: string;
    tittel: string;
};

export type TidslinjeHendelseType_fpoversikt =
    | 'FØRSTEGANGSSØKNAD'
    | 'FØRSTEGANGSSØKNAD_NY'
    | 'ETTERSENDING'
    | 'ENDRINGSSØKNAD'
    | 'INNTEKTSMELDING'
    | 'VEDTAK'
    | 'UTGÅENDE_INNHENT_OPPLYSNINGER'
    | 'UTGÅENDE_ETTERLYS_INNTEKTSMELDING'
    | 'FORELDREPENGER_FEIL_PRAKSIS_UTSETTELSE_INFOBREV'
    | 'UTGÅENDE_VARSEL_TILBAKEBETALING';

export type KontoBeregningDto_fpoversikt = {
    kontoer: KontoDto_fpoversikt[];
    minsteretter: Minsteretter_fpoversikt;
    tillegg?: Tillegg_fpoversikt;
};

export type KontoDto_fpoversikt = {
    dager: number;
    konto: KontoTypeUttak_fpoversikt;
};

export type KontoTypeUttak_fpoversikt =
    | 'MØDREKVOTE'
    | 'FEDREKVOTE'
    | 'FELLESPERIODE'
    | 'FORELDREPENGER'
    | 'FORELDREPENGER_FØR_FØDSEL'
    | 'AKTIVITETSFRI_KVOTE';

export type Minsteretter_fpoversikt = {
    farRundtFødsel: number;
    toTette: number;
};

export type Tillegg_fpoversikt = {
    flerbarn: number;
    prematur: number;
};

export type KontoBeregningGrunnlagDto_fpoversikt = {
    antallBarn: number;
    brukerrolle: Brukerrolle_fpoversikt;
    familieHendelseDatoNesteSak?: string;
    fødselsdato?: string;
    morHarUføretrygd?: boolean;
    omsorgsovertakelseDato?: string;
    rettighetstype: Rettighetstype_fpoversikt;
    termindato?: string;
};

export type Brukerrolle_fpoversikt = 'MOR' | 'FAR' | 'MEDMOR' | 'UKJENT';

export type Rettighetstype_fpoversikt = 'ALENEOMSORG' | 'BARE_SØKER_RETT' | 'BEGGE_RETT';

export type HentMineFrilansoppdragData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/arbeid/mineFrilansoppdrag';
};

export type HentMineFrilansoppdragResponses = {
    /**
     * default response
     */
    default: EksternArbeidsforholdDto_fpoversikt[];
};

export type HentMineFrilansoppdragResponse = HentMineFrilansoppdragResponses[keyof HentMineFrilansoppdragResponses];

export type HentMittArbeidData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/arbeid/mineArbeidsforhold';
};

export type HentMittArbeidResponses = {
    /**
     * default response
     */
    default: EksternArbeidsforholdDto_fpoversikt[];
};

export type HentMittArbeidResponse = HentMittArbeidResponses[keyof HentMittArbeidResponses];

export type TrengerDokumentereMorsArbeidData = {
    body: MorArbeidRequest_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/arbeid/morDokumentasjon';
};

export type TrengerDokumentereMorsArbeidResponses = {
    /**
     * default response
     */
    default: boolean;
};

export type TrengerDokumentereMorsArbeidResponse =
    TrengerDokumentereMorsArbeidResponses[keyof TrengerDokumentereMorsArbeidResponses];

export type AlleDokumenterPåSakData = {
    body?: never;
    path?: never;
    query: {
        saksnummer: string;
    };
    url: '/api/dokument/alle';
};

export type AlleDokumenterPåSakResponses = {
    /**
     * default response
     */
    default: DokumentDto_fpoversikt[];
};

export type AlleDokumenterPåSakResponse = AlleDokumenterPåSakResponses[keyof AlleDokumenterPåSakResponses];

export type DokumentData = {
    body?: never;
    path?: never;
    query: {
        journalpostId: string;
        dokumentId: string;
    };
    url: '/api/dokument';
};

export type DokumentResponses = {
    /**
     * default response
     */
    default: string;
};

export type DokumentResponse = DokumentResponses[keyof DokumentResponses];

export type OppdaterOppgaverData = {
    /**
     * Liste med saksnummre som skal oppdateres
     */
    body: string[];
    path?: never;
    query?: never;
    url: '/api/forvaltningSaker/oppdaterOppgaver';
};

export type OppdaterOppgaverResponses = {
    /**
     * Task for å oppdatere oppgaver er opprettet per sak
     */
    200: unknown;
};

export type OpprettHentSakTaskForSaksnummreData = {
    /**
     * Liste med saksnummre som skal oppdateres
     */
    body: string[];
    path?: never;
    query?: never;
    url: '/api/forvaltningSaker/oppdater';
};

export type OpprettHentSakTaskForSaksnummreErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type OpprettHentSakTaskForSaksnummreResponses = {
    /**
     * HentSakTask opprettet for alle saknsummre
     */
    200: unknown;
};

export type CreateProsessTaskData = {
    /**
     * Informasjon for restart en eksisterende prosesstask
     */
    body?: ProsessTaskOpprettInputDto_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/prosesstask/create';
};

export type CreateProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type CreateProsessTaskResponses = {
    /**
     * Prosesstaskens oppdatert informasjon
     */
    202: ProsessTaskDataDto_fpoversikt;
};

export type CreateProsessTaskResponse = CreateProsessTaskResponses[keyof CreateProsessTaskResponses];

export type FinnFeiletProsessTaskData = {
    body?: never;
    path: {
        prosessTaskId: number;
    };
    query?: never;
    url: '/api/prosesstask/feil/{prosessTaskId}';
};

export type FinnFeiletProsessTaskErrors = {
    /**
     * Feil input
     */
    400: unknown;
    /**
     * Tom respons når angitt prosesstask-id ikke finnes
     */
    404: unknown;
};

export type FinnFeiletProsessTaskResponses = {
    /**
     * Angitt prosesstask-id finnes
     */
    200: FeiletProsessTaskDataDto_fpoversikt;
};

export type FinnFeiletProsessTaskResponse = FinnFeiletProsessTaskResponses[keyof FinnFeiletProsessTaskResponses];

export type FinnProsessTasksData = {
    body?: never;
    path: {
        /**
         * Task status som skal hentes.
         */
        prosessTaskStatus: IkkeFerdigProsessTaskStatusEnum_fpoversikt;
    };
    query?: never;
    url: '/api/prosesstask/list/{prosessTaskStatus}';
};

export type FinnProsessTasksResponses = {
    /**
     * Liste over prosesstasker, eller tom liste når angitt/default søkefilter ikke finner noen prosesstasker
     */
    200: ProsessTaskDataDto_fpoversikt;
};

export type FinnProsessTasksResponse = FinnProsessTasksResponses[keyof FinnProsessTasksResponses];

export type RestartProsessTaskData = {
    body?: never;
    path: {
        prosessTaskId: number;
        prosessTaskStatus: FeiletProsessTaskStatusEnum_fpoversikt;
    };
    query?: never;
    url: '/api/prosesstask/launch/{prosessTaskId}/{prosessTaskStatus}';
};

export type RestartProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type RestartProsessTaskResponses = {
    /**
     * Prosesstaskens oppdatert informasjon
     */
    200: ProsessTaskRestartResultatDto_fpoversikt;
};

export type RestartProsessTaskResponse = RestartProsessTaskResponses[keyof RestartProsessTaskResponses];

export type RetryAllProsessTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/prosesstask/retryall';
};

export type RetryAllProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type RetryAllProsessTaskResponses = {
    /**
     * Response med liste av prosesstasks som restartes
     */
    200: ProsessTaskRetryAllResultatDto_fpoversikt;
};

export type RetryAllProsessTaskResponse = RetryAllProsessTaskResponses[keyof RetryAllProsessTaskResponses];

export type SearchProsessTasksData = {
    /**
     * Søkefilter for å begrense resultatet av returnerte prosesstask.
     */
    body?: SokeFilterDto_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/prosesstask/search';
};

export type SearchProsessTasksResponses = {
    /**
     * Liste over prosesstasker, eller tom liste når angitt/default søkefilter ikke finner noen prosesstasker
     */
    200: ProsessTaskDataDto_fpoversikt;
};

export type SearchProsessTasksResponse = SearchProsessTasksResponses[keyof SearchProsessTasksResponses];

export type SetFeiletProsessTaskFerdigData = {
    body?: never;
    path: {
        prosessTaskId: number;
        prosessTaskStatus: IkkeFerdigProsessTaskStatusEnum_fpoversikt;
    };
    query?: never;
    url: '/api/prosesstask/setferdig/{prosessTaskId}/{prosessTaskStatus}';
};

export type SetFeiletProsessTaskFerdigErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type SetFeiletProsessTaskFerdigResponses = {
    /**
     * Angitt prosesstask-id satt til status FERDIG
     */
    200: unknown;
};

export type AlleInntektsmeldingerData = {
    body?: never;
    path?: never;
    query: {
        saksnummer: string;
    };
    url: '/api/inntektsmeldinger';
};

export type AlleInntektsmeldingerResponses = {
    /**
     * default response
     */
    default: FpOversiktInntektsmeldingDto_fpoversikt[];
};

export type AlleInntektsmeldingerResponse = AlleInntektsmeldingerResponses[keyof AlleInntektsmeldingerResponses];

export type ManglendeVedleggData = {
    body?: never;
    path?: never;
    query: {
        saksnummer: string;
    };
    url: '/api/oppgaver/manglendevedlegg';
};

export type ManglendeVedleggResponses = {
    /**
     * default response
     */
    default: DokumentType_fpoversikt[];
};

export type ManglendeVedleggResponse = ManglendeVedleggResponses[keyof ManglendeVedleggResponses];

export type TilbakekrevingsuttalelserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/oppgaver/tilbakekrevingsuttalelse';
};

export type TilbakekrevingsuttalelserResponses = {
    /**
     * default response
     */
    default: TilbakekrevingUttalelseOppgave_fpoversikt[];
};

export type TilbakekrevingsuttalelserResponse =
    TilbakekrevingsuttalelserResponses[keyof TilbakekrevingsuttalelserResponses];

export type PersoninfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/person/info';
};

export type PersoninfoResponses = {
    /**
     * default response
     */
    default: PersonDto_fpoversikt;
};

export type PersoninfoResponse = PersoninfoResponses[keyof PersoninfoResponses];

export type SøkerinfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/person/info-med-arbeidsforhold';
};

export type SøkerinfoResponses = {
    /**
     * default response
     */
    default: PersonMedArbeidsforholdDto_fpoversikt;
};

export type SøkerinfoResponse = SøkerinfoResponses[keyof SøkerinfoResponses];

export type AktøridForPersonData = {
    body: AnnenPartRequest_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/annenPart/aktorid';
};

export type AktøridForPersonResponses = {
    /**
     * default response
     */
    default: string;
};

export type AktøridForPersonResponse = AktøridForPersonResponses[keyof AktøridForPersonResponses];

export type HentData = {
    body: AnnenPartRequest_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/annenPart/v2';
};

export type HentResponses = {
    /**
     * default response
     */
    default: AnnenPartSak_fpoversikt;
};

export type HentResponse = HentResponses[keyof HentResponses];

export type HentVedtakData = {
    body: AnnenPartRequest_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/annenPart';
};

export type HentVedtakResponses = {
    /**
     * default response
     */
    default: AnnenPartSak_fpoversikt;
};

export type HentVedtakResponse = HentVedtakResponses[keyof HentVedtakResponses];

export type ErSakOppdatertEtterMottattSøknadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/saker/erOppdatert';
};

export type ErSakOppdatertEtterMottattSøknadResponses = {
    /**
     * default response
     */
    default: boolean;
};

export type ErSakOppdatertEtterMottattSøknadResponse =
    ErSakOppdatertEtterMottattSøknadResponses[keyof ErSakOppdatertEtterMottattSøknadResponses];

export type Hent1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/saker';
};

export type Hent1Responses = {
    /**
     * default response
     */
    default: Saker_fpoversikt;
};

export type Hent1Response = Hent1Responses[keyof Hent1Responses];

export type HentTidslinjeData = {
    body?: never;
    path?: never;
    query: {
        saksnummer: string;
    };
    url: '/api/tidslinje';
};

export type HentTidslinjeResponses = {
    /**
     * default response
     */
    default: TidslinjeHendelseDto_fpoversikt[];
};

export type HentTidslinjeResponse = HentTidslinjeResponses[keyof HentTidslinjeResponses];

export type Personinfo1Data = {
    body: KontoBeregningGrunnlagDto_fpoversikt;
    path?: never;
    query?: never;
    url: '/api/konto';
};

export type Personinfo1Responses = {
    /**
     * default response
     */
    default: {
        [key: string]: KontoBeregningDto_fpoversikt;
    };
};

export type Personinfo1Response = Personinfo1Responses[keyof Personinfo1Responses];
