// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/fpsoknad` | (string & {});
};

export type no_nav_foreldrepenger_kontrakter_felles_kodeverk_KontoType =
    'FELLESPERIODE' | 'MØDREKVOTE' | 'FEDREKVOTE' | 'FORELDREPENGER' | 'FORELDREPENGER_FØR_FØDSEL';

export type no_nav_foreldrepenger_kontrakter_felles_kodeverk_MorsAktivitet =
    | 'ARBEID'
    | 'UTDANNING'
    | 'KVALPROG'
    | 'INTROPROG'
    | 'TRENGER_HJELP'
    | 'INNLAGT'
    | 'ARBEID_OG_UTDANNING'
    | 'UFØRE'
    | 'IKKE_OPPGITT';

export type no_nav_foreldrepenger_kontrakter_felles_kodeverk_Overføringsårsak =
    'INSTITUSJONSOPPHOLD_ANNEN_FORELDER' | 'SYKDOM_ANNEN_FORELDER' | 'ALENEOMSORG' | 'IKKE_RETT_ANNEN_FORELDER';

export type BrukerRolle = 'MOR' | 'FAR' | 'MEDMOR';

export type EndringssøknadForeldrepengerDto = {
    annenForelder?: AnnenForelderDto;
    barn: BarnDto;
    mottattdato?: string;
    rolle?: BrukerRolle;
    saksnummer: string;
    språkkode?: Målform;
    søkerinfo: SøkerDto;
    uttaksplan: UttaksplanDto;
    vedlegg?: VedleggDto[];
};

export type Målform = 'NB' | 'NN' | 'EN' | 'E';

export type SøkerDto = {
    arbeidsforhold?: Arbeidsforhold[];
    fnr: string;
    frilansoppdrag?: Frilansoppdrag[];
    navn: Navn;
    selvstendigNæring?: SelvstendigNæring[];
};

export type Arbeidsforhold = {
    fom?: string;
    navn?: string;
    orgnummer?: string;
    stillingsprosent?: number;
    tom?: string;
};

export type Frilansoppdrag = {
    fom?: string;
    navn?: string;
    tom?: string;
};

export type SelvstendigNæring = {
    navn?: string;
    næringstype?: Virksomhetstype;
    organisasjonsnummer?: string;
};

export type Navn = {
    etternavn: string;
    fornavn: string;
    mellomnavn?: string;
};

export type AdopsjonDto = {
    adopsjonAvEktefellesBarn: boolean;
    adopsjonsdato: string;
    ankomstdato?: string;
    antallBarn?: number;
    fødselsdatoer?: string[];
    søkerAdopsjonAlene?: boolean;
};

export type BarnDto = (
    | ({
          type: 'adopsjon';
      } & AdopsjonDto)
    | ({
          type: 'fødsel';
      } & FødselDto)
    | ({
          type: 'omsorgsovertakelse';
      } & OmsorgsovertakelseDto)
    | ({
          type: 'termin';
      } & TerminDto)
) & {
    type: string;
};

export type FødselDto = {
    antallBarn?: number;
    fødselsdato: string;
    termindato?: string;
};

export type OmsorgsovertakelseDto = {
    antallBarn?: number;
    foreldreansvarsdato: string;
    fødselsdatoer?: string[];
};

export type TerminDto = {
    antallBarn?: number;
    terminbekreftelseDato?: string;
    termindato: string;
};

export type AnnenForelderDto = (
    | ({
          type: 'norsk';
      } & NorskForelderDto)
    | ({
          type: 'utenlandsk';
      } & UtenlandskForelderDto)
) & {
    type: string;
};

export type Rettigheter = {
    erAleneOmOmsorg?: boolean;
    erInformertOmSøknaden?: boolean;
    harAnnenForelderOppholdtSegIEØS?: boolean;
    harAnnenForelderTilsvarendeRettEØS?: boolean;
    harMorUføretrygd?: boolean;
    harRettPåForeldrepenger: boolean;
};

export type NorskForelderDto = {
    etternavn: string;
    fnr: string;
    fornavn: string;
    rettigheter: Rettigheter;
};

export type UtenlandskForelderDto = {
    bostedsland: string;
    etternavn: string;
    fnr: string;
    fornavn: string;
    rettigheter: Rettigheter;
};

export type OppholdsPeriodeDto = {
    fom: string;
    tom: string;
    årsak: Oppholdsårsak;
};

export type Oppholdsårsak =
    | 'INGEN'
    | 'UTTAK_MØDREKVOTE_ANNEN_FORELDER'
    | 'UTTAK_FEDREKVOTE_ANNEN_FORELDER'
    | 'UTTAK_FORELDREPENGER_ANNEN_FORELDER'
    | 'UTTAK_FELLESP_ANNEN_FORELDER';

export type OverføringsPeriodeDto = {
    fom: string;
    tom: string;
    konto: no_nav_foreldrepenger_kontrakter_felles_kodeverk_KontoType;
    årsak: no_nav_foreldrepenger_kontrakter_felles_kodeverk_Overføringsårsak;
};

export type UtsettelsesPeriodeDto = {
    fom: string;
    tom: string;
    erArbeidstaker?: boolean;
    morsAktivitetIPerioden?: no_nav_foreldrepenger_kontrakter_felles_kodeverk_MorsAktivitet;
    årsak: UtsettelsesÅrsak;
};

export type UtsettelsesÅrsak =
    | 'ARBEID'
    | 'LOVBESTEMT_FERIE'
    | 'SYKDOM'
    | 'FRI'
    | 'INSTITUSJONSOPPHOLD_SØKER'
    | 'INSTITUSJONSOPPHOLD_BARNET'
    | 'HV_OVELSE'
    | 'NAV_TILTAK';

export type UttaksPeriodeDto = {
    fom: string;
    tom: string;
    gradering?: GraderingDto;
    konto: no_nav_foreldrepenger_kontrakter_felles_kodeverk_KontoType;
    morsAktivitetIPerioden?: no_nav_foreldrepenger_kontrakter_felles_kodeverk_MorsAktivitet;
    samtidigUttakProsent?: number;
    ønskerFlerbarnsdager?: boolean;
    ønskerGradering?: boolean;
    ønskerSamtidigUttak?: boolean;
};

export type GraderingDto = {
    erArbeidstaker?: boolean;
    erFrilanser?: boolean;
    erSelvstendig?: boolean;
    orgnumre?: string[];
    stillingsprosent: number;
};

export type UttaksplanDto = {
    uttaksperioder: Uttaksplanperiode[];
    ønskerJustertUttakVedFødsel?: boolean;
};

export type Uttaksplanperiode = (
    | ({
          type: 'opphold';
      } & OppholdsPeriodeDto)
    | ({
          type: 'overføring';
      } & OverføringsPeriodeDto)
    | ({
          type: 'utsettelse';
      } & UtsettelsesPeriodeDto)
    | ({
          type: 'uttak';
      } & UttaksPeriodeDto)
) & {
    type: string;
};

export type ArbeidsforholdDto = (
    | ({
          type: 'frilanser';
      } & FrilanserDto)
    | ({
          type: 'privat';
      } & PrivatArbeidsgiverDto)
    | ({
          type: 'selvstendig';
      } & SelvstendigNæringsdrivendeDto)
    | ({
          type: 'virksomhet';
      } & VirksomhetDto)
) & {
    type: string;
};

export type FrilanserDto = {
    [key: string]: unknown;
};

export type PrivatArbeidsgiverDto = {
    id: string;
};

export type SelvstendigNæringsdrivendeDto = {
    [key: string]: unknown;
};

export type VirksomhetDto = {
    id: string;
};

export type DokumentTypeId =
    | 'I000001'
    | 'I000002'
    | 'I000003'
    | 'I000004'
    | 'I000005'
    | 'I000050'
    | 'I000007'
    | 'I000023'
    | 'I000032'
    | 'I000036'
    | 'I000037'
    | 'I000038'
    | 'I000039'
    | 'I000042'
    | 'I000044'
    | 'I000051'
    | 'I000061'
    | 'I000062'
    | 'I000063'
    | 'I000066'
    | 'I000065'
    | 'I000109'
    | 'I000110'
    | 'I000111'
    | 'I000112'
    | 'I000114'
    | 'I000116'
    | 'I000117'
    | 'I000118'
    | 'I000119'
    | 'I000120'
    | 'I000121'
    | 'I000122'
    | 'I000123'
    | 'I000124'
    | 'I000130'
    | 'I000131'
    | 'I000132'
    | 'I000133'
    | 'I000140'
    | 'I000141'
    | 'I000143'
    | 'I000144'
    | 'I000145'
    | 'I000146'
    | 'I000060';

export type Dokumenterer = {
    arbeidsforhold?: ArbeidsforholdDto;
    perioder?: ÅpenPeriodeDto[];
    type: DokumentererType;
};

export type DokumentererType = 'BARN' | 'OPPTJENING' | 'UTTAK' | 'TILRETTELEGGING';

export type InnsendingType = 'LASTET_OPP' | 'SEND_SENERE' | 'AUTOMATISK';

export type VedleggDto = {
    beskrivelse?: string;
    dokumenterer?: Dokumenterer;
    innsendingsType: InnsendingType;
    skjemanummer: DokumentTypeId;
    uuid?: string;
};

export type ÅpenPeriodeDto = {
    fom: string;
    tom?: string;
};

export type EngangsstønadDto = {
    barn: BarnDto;
    mottattdato?: string;
    språkkode: Målform;
    søkerinfo: SøkerDto;
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    vedlegg?: VedleggDto[];
};

export type UtenlandsoppholdsperiodeDto = {
    fom: string;
    landkode: string;
    tom: string;
};

export type ForeldrepengesøknadDto = {
    andreInntekterSiste10Mnd?: AnnenInntektDto[];
    annenForelder?: AnnenForelderDto;
    barn: BarnDto;
    dekningsgrad: Dekningsgrad;
    egenNæring?: NæringDto;
    frilans?: FrilansDto;
    mottattdato?: string;
    rolle?: BrukerRolle;
    språkkode?: Målform;
    søkerinfo: SøkerDto;
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    uttaksplan: UttaksplanDto;
    vedlegg?: VedleggDto[];
};

export type Dekningsgrad = '80' | '100';

export type AnnenInntektDto = {
    arbeidsgiverNavn?: string;
    fom: string;
    land?: string;
    tom?: string;
    type: AnnenOpptjeningType;
};

export type AnnenOpptjeningType =
    | 'ETTERLØNN_SLUTTPAKKE'
    | 'ETTERLØNN_ARBEIDSGIVER'
    | 'JOBB_I_UTLANDET'
    | 'LØNN_UNDER_UTDANNING'
    | 'MILITÆR_ELLER_SIVILTJENESTE'
    | 'SLUTTPAKKE'
    | 'VENTELØNN_VARTPENGER'
    | 'VENTELØNN'
    | 'VARTPENGER';

export type FrilansDto = {
    oppstart: string;
    tom?: string;
};

export type NæringDto = {
    fom: string;
    harBlittYrkesaktivILøpetAvDeTreSisteFerdigliknedeÅrene?: boolean;
    hattVarigEndringAvNæringsinntektSiste4Kalenderår?: boolean;
    navnPåNæringen?: string;
    næringsinntekt?: number;
    næringstype: Virksomhetstype;
    oppstartsdato?: string;
    organisasjonsnummer?: string;
    registrertILand?: string;
    registrertINorge: boolean;
    tom?: string;
    varigEndringBeskrivelse?: string;
    varigEndringDato?: string;
    varigEndringInntektEtterEndring?: number;
};

export type Virksomhetstype = 'ANNEN' | 'JORDBRUK_SKOGBRUK' | 'FISKE' | 'DAGMAMMA';

export type SvangerskapspengesøknadDto = {
    andreInntekterSiste10Mnd?: AnnenInntektDto[];
    avtaltFerie: AvtaltFerieDto[];
    barn: BarnSvpDto;
    egenNæring?: NæringDto;
    frilans?: FrilansDto;
    mottattdato?: string;
    språkkode: Målform;
    søkerinfo: SøkerDto;
    tilretteleggingsbehov: TilretteleggingbehovDto[];
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    vedlegg: VedleggDto[];
};

export type AvtaltFerieDto = {
    arbeidsforhold: ArbeidsforholdDto;
    fom: string;
    tom: string;
};

export type BarnSvpDto = {
    fødselsdato?: string;
    termindato: string;
};

export type TilretteleggingbehovDto = {
    arbeidsforhold: ArbeidsforholdDto;
    behovForTilretteleggingFom: string;
    risikofaktorer?: string;
    tilrettelegginger?: TilretteleggingDto[];
    tilretteleggingstiltak?: string;
};

export type TilretteleggingDto = (
    | ({
          type: 'delvis';
      } & Del)
    | ({
          type: 'hel';
      } & Hel)
    | ({
          type: 'ingen';
      } & Ingen)
) & {
    type: string;
};

export type Del = {
    fom: string;
    stillingsprosent: number;
};

export type Hel = {
    fom: string;
};

export type Ingen = {
    fom: string;
};

export type BrukerTekstDto = {
    dokumentType: DokumentTypeId;
    tekst: string;
};

export type EttersendelseDto = {
    brukerTekst?: BrukerTekstDto;
    fnr: string;
    mottattdato?: string;
    saksnummer: string;
    type: YtelseType;
    vedlegg: VedleggDto[];
};

export type YtelseType = 'FORELDREPENGER' | 'SVANGERSKAPSPENGER' | 'ENGANGSSTØNAD';

export type ForsendelseStatus = {
    saksnummer?: string;
    status: Status;
};

export type Status = 'PENDING' | 'MIDLERTIDIG' | 'ENDELIG' | 'FORSENDELSE_FINNES_IKKE';

export type YtelseMellomlagringType = 'FORELDREPENGER' | 'SVANGERSKAPSPENGER' | 'ENGANGSSTONAD';

export type org_glassfish_jersey_media_multipart_FormDataContentDisposition = {
    creationDate?: string;
    encoded?: boolean;
    fileName?: string;
    modificationDate?: string;
    name?: string;
    parameters?: {
        [key: string]: string;
    };
    readDate?: string;
    size?: number;
    type?: {
        empty?: boolean;
    };
};
