// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AdopsjonDto = BarnDto & {
    type: 'adopsjon';
} & {
    antallBarn?: number;
    fødselsdatoer?: string[];
    adopsjonsdato: string;
    ankomstdato?: string;
    adopsjonAvEktefellesBarn: boolean;
    søkerAdopsjonAlene?: boolean;
};

export type AnnenForelderDto = {
    type: string;
};

export type Arbeidsforhold = {
    navn?: string;
    orgnummer?: string;
    stillingsprosent?: number;
    fom?: string;
    tom?: string;
};

export type ArbeidsforholdDto = {
    type: string;
};

export type BarnDto = {
    type: string;
};

export type BrukerRolle = 'MOR' | 'FAR' | 'MEDMOR' | 'IKKE_RELEVANT';

export type CountryCode =
    | 'UNDEFINED'
    | 'AC'
    | 'AD'
    | 'AE'
    | 'AF'
    | 'AG'
    | 'AI'
    | 'AL'
    | 'AM'
    | 'AN'
    | 'AO'
    | 'AQ'
    | 'AR'
    | 'AS'
    | 'AT'
    | 'AU'
    | 'AW'
    | 'AX'
    | 'AZ'
    | 'BA'
    | 'BB'
    | 'BD'
    | 'BE'
    | 'BF'
    | 'BG'
    | 'BH'
    | 'BI'
    | 'BJ'
    | 'BL'
    | 'BM'
    | 'BN'
    | 'BO'
    | 'BQ'
    | 'BR'
    | 'BS'
    | 'BT'
    | 'BU'
    | 'BV'
    | 'BW'
    | 'BY'
    | 'BZ'
    | 'CA'
    | 'CC'
    | 'CD'
    | 'CF'
    | 'CG'
    | 'CH'
    | 'CI'
    | 'CK'
    | 'CL'
    | 'CM'
    | 'CN'
    | 'CO'
    | 'CP'
    | 'CR'
    | 'CS'
    | 'CU'
    | 'CV'
    | 'CW'
    | 'CX'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DG'
    | 'DJ'
    | 'DK'
    | 'DM'
    | 'DO'
    | 'DZ'
    | 'EA'
    | 'EC'
    | 'EE'
    | 'EG'
    | 'EH'
    | 'ER'
    | 'ES'
    | 'ET'
    | 'EU'
    | 'EZ'
    | 'FI'
    | 'FJ'
    | 'FK'
    | 'FM'
    | 'FO'
    | 'FR'
    | 'FX'
    | 'GA'
    | 'GB'
    | 'GD'
    | 'GE'
    | 'GF'
    | 'GG'
    | 'GH'
    | 'GI'
    | 'GL'
    | 'GM'
    | 'GN'
    | 'GP'
    | 'GQ'
    | 'GR'
    | 'GS'
    | 'GT'
    | 'GU'
    | 'GW'
    | 'GY'
    | 'HK'
    | 'HM'
    | 'HN'
    | 'HR'
    | 'HT'
    | 'HU'
    | 'IC'
    | 'ID'
    | 'IE'
    | 'IL'
    | 'IM'
    | 'IN'
    | 'IO'
    | 'IQ'
    | 'IR'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'JM'
    | 'JO'
    | 'JP'
    | 'KE'
    | 'KG'
    | 'KH'
    | 'KI'
    | 'KM'
    | 'KN'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KY'
    | 'KZ'
    | 'LA'
    | 'LB'
    | 'LC'
    | 'LI'
    | 'LK'
    | 'LR'
    | 'LS'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'LY'
    | 'MA'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MF'
    | 'MG'
    | 'MH'
    | 'MK'
    | 'ML'
    | 'MM'
    | 'MN'
    | 'MO'
    | 'MP'
    | 'MQ'
    | 'MR'
    | 'MS'
    | 'MT'
    | 'MU'
    | 'MV'
    | 'MW'
    | 'MX'
    | 'MY'
    | 'MZ'
    | 'NA'
    | 'NC'
    | 'NE'
    | 'NF'
    | 'NG'
    | 'NI'
    | 'NL'
    | 'NO'
    | 'NP'
    | 'NR'
    | 'NT'
    | 'NU'
    | 'NZ'
    | 'OM'
    | 'PA'
    | 'PE'
    | 'PF'
    | 'PG'
    | 'PH'
    | 'PK'
    | 'PL'
    | 'PM'
    | 'PN'
    | 'PR'
    | 'PS'
    | 'PT'
    | 'PW'
    | 'PY'
    | 'QA'
    | 'RE'
    | 'RO'
    | 'RS'
    | 'RU'
    | 'RW'
    | 'SA'
    | 'SB'
    | 'SC'
    | 'SD'
    | 'SE'
    | 'SF'
    | 'SG'
    | 'SH'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SL'
    | 'SM'
    | 'SN'
    | 'SO'
    | 'SR'
    | 'SS'
    | 'ST'
    | 'SU'
    | 'SV'
    | 'SX'
    | 'SY'
    | 'SZ'
    | 'TA'
    | 'TC'
    | 'TD'
    | 'TF'
    | 'TG'
    | 'TH'
    | 'TJ'
    | 'TK'
    | 'TL'
    | 'TM'
    | 'TN'
    | 'TO'
    | 'TP'
    | 'TR'
    | 'TT'
    | 'TV'
    | 'TW'
    | 'TZ'
    | 'UA'
    | 'UG'
    | 'UK'
    | 'UM'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VA'
    | 'VC'
    | 'VE'
    | 'VG'
    | 'VI'
    | 'VN'
    | 'VU'
    | 'WF'
    | 'WS'
    | 'XI'
    | 'XU'
    | 'XK'
    | 'YE'
    | 'YT'
    | 'YU'
    | 'ZA'
    | 'ZM'
    | 'ZR'
    | 'ZW';

export type DokumentTypeId =
    | 'I000001'
    | 'I000002'
    | 'I000003'
    | 'I000004'
    | 'I000005'
    | 'I000050'
    | 'I000007'
    | 'I000023'
    | 'I000032'
    | 'I000036'
    | 'I000037'
    | 'I000038'
    | 'I000039'
    | 'I000042'
    | 'I000044'
    | 'I000051'
    | 'I000061'
    | 'I000062'
    | 'I000063'
    | 'I000066'
    | 'I000065'
    | 'I000109'
    | 'I000110'
    | 'I000111'
    | 'I000112'
    | 'I000114'
    | 'I000116'
    | 'I000117'
    | 'I000118'
    | 'I000119'
    | 'I000120'
    | 'I000121'
    | 'I000122'
    | 'I000123'
    | 'I000124'
    | 'I000130'
    | 'I000131'
    | 'I000132'
    | 'I000133'
    | 'I000140'
    | 'I000141'
    | 'I000143'
    | 'I000144'
    | 'I000145'
    | 'I000146'
    | 'I000060';

export type Dokumenterer = {
    type: DokumentererType;
    arbeidsforhold?: ArbeidsforholdDto;
    perioder?: ÅpenPeriodeDto[];
};

export type DokumentererType = 'BARN' | 'OPPTJENING' | 'UTTAK' | 'TILRETTELEGGING';

export type EndringssøknadForeldrepengerDto = {
    mottattdato?: string;
    saksnummer: string;
    søkerinfo: SøkerDto;
    rolle?: BrukerRolle;
    språkkode?: Målform;
    barn: BarnDto;
    annenForelder?: AnnenForelderDto;
    uttaksplan: UttaksplanDto;
    vedlegg?: VedleggDto[];
};

export type FrilanserDto = ArbeidsforholdDto & {
    type: 'FrilanserDto';
};

export type FødselDto = BarnDto & {
    type: 'fødsel';
} & {
    antallBarn?: number;
    fødselsdato: string;
    termindato?: string;
};

export type GraderingDto = {
    stillingsprosent: number;
    erArbeidstaker?: boolean;
    erFrilanser?: boolean;
    erSelvstendig?: boolean;
    orgnumre?: string[];
};

export type KontoType = 'FELLESPERIODE' | 'MØDREKVOTE' | 'FEDREKVOTE' | 'FORELDREPENGER' | 'FORELDREPENGER_FØR_FØDSEL';

export type MorsAktivitet =
    | 'ARBEID'
    | 'UTDANNING'
    | 'KVALPROG'
    | 'INTROPROG'
    | 'TRENGER_HJELP'
    | 'INNLAGT'
    | 'ARBEID_OG_UTDANNING'
    | 'UFØRE'
    | 'IKKE_OPPGITT';

export type Målform = 'NB' | 'NN' | 'EN' | 'E';

export type NorskForelderDto = AnnenForelderDto & {
    type: 'norsk';
} & {
    fnr: string;
    fornavn: string;
    etternavn: string;
    rettigheter: Rettigheter;
};

export type OmsorgsovertakelseDto = BarnDto & {
    type: 'omsorgsovertakelse';
} & {
    antallBarn?: number;
    fødselsdatoer?: string[];
    foreldreansvarsdato: string;
};

export type OppholdsPeriodeDto = Uttaksplanperiode & {
    type: 'opphold';
} & {
    fom: string;
    tom: string;
    årsak: Oppholdsårsak;
};

export type Oppholdsårsak =
    | 'INGEN'
    | 'UTTAK_MØDREKVOTE_ANNEN_FORELDER'
    | 'UTTAK_FEDREKVOTE_ANNEN_FORELDER'
    | 'UTTAK_FORELDREPENGER_ANNEN_FORELDER'
    | 'UTTAK_FELLESP_ANNEN_FORELDER';

export type OverføringsPeriodeDto = Uttaksplanperiode & {
    type: 'overføring';
} & {
    fom: string;
    tom: string;
    årsak: Overføringsårsak;
    konto: KontoType;
};

export type Overføringsårsak =
    | 'INSTITUSJONSOPPHOLD_ANNEN_FORELDER'
    | 'SYKDOM_ANNEN_FORELDER'
    | 'ALENEOMSORG'
    | 'IKKE_RETT_ANNEN_FORELDER';

export type PrivatArbeidsgiverDto = ArbeidsforholdDto & {
    type: 'PrivatArbeidsgiverDto';
} & {
    id: string;
};

export type Rettigheter = {
    harRettPåForeldrepenger: boolean;
    erInformertOmSøknaden?: boolean;
    erAleneOmOmsorg?: boolean;
    harMorUføretrygd?: boolean;
    harAnnenForelderOppholdtSegIEØS?: boolean;
    harAnnenForelderTilsvarendeRettEØS?: boolean;
};

export type SelvstendigNæringsdrivendeDto = ArbeidsforholdDto & {
    type: 'SelvstendigNæringsdrivendeDto';
};

export type SøkerDto = {
    fnr: string;
    navn: { fornavn: string; mellomnavn?: string; etternavn: string };
    arbeidsforhold?: Arbeidsforhold[];
};

export type TerminDto = BarnDto & {
    type: 'termin';
} & {
    antallBarn?: number;
    termindato: string;
    terminbekreftelseDato?: string;
};

export type UtenlandskForelderDto = AnnenForelderDto & {
    type: 'utenlandsk';
} & {
    fnr: string;
    fornavn: string;
    etternavn: string;
    bostedsland: CountryCode;
    rettigheter: Rettigheter;
};

export type UtsettelsesPeriodeDto = Uttaksplanperiode & {
    type: 'utsettelse';
} & {
    fom: string;
    tom: string;
    årsak: UtsettelsesÅrsak;
    morsAktivitetIPerioden?: MorsAktivitet;
    erArbeidstaker?: boolean;
};

export type UtsettelsesÅrsak =
    | 'ARBEID'
    | 'LOVBESTEMT_FERIE'
    | 'SYKDOM'
    | 'FRI'
    | 'INSTITUSJONSOPPHOLD_SØKER'
    | 'INSTITUSJONSOPPHOLD_BARNET'
    | 'HV_OVELSE'
    | 'NAV_TILTAK';

export type UttaksPeriodeDto = Uttaksplanperiode & {
    type: 'uttak';
} & {
    fom: string;
    tom: string;
    konto: KontoType;
    morsAktivitetIPerioden?: MorsAktivitet;
    ønskerSamtidigUttak?: boolean;
    ønskerFlerbarnsdager?: boolean;
    samtidigUttakProsent?: number;
    gradering?: GraderingDto;
};

export type UttaksplanDto = {
    ønskerJustertUttakVedFødsel?: boolean;
    uttaksperioder: Uttaksplanperiode[];
};

export type Uttaksplanperiode = {
    type: string;
};

export type VedleggDto = {
    uuid: string;
    skjemanummer: DokumentTypeId;
    innsendingsType?: VedleggInnsendingType;
    beskrivelse?: string;
    dokumenterer?: Dokumenterer;
};

export type VedleggInnsendingType = 'LASTET_OPP' | 'SEND_SENERE' | 'AUTOMATISK';

export type VirksomhetDto = ArbeidsforholdDto & {
    type: 'VirksomhetDto';
} & {
    id: string;
};

export type ÅpenPeriodeDto = {
    fom: string;
    tom?: string;
};

export type EngangsstønadDto = {
    mottattdato?: string;
    søkerinfo: SøkerDto;
    språkkode: Målform;
    rolle?: BrukerRolle;
    barn: BarnDto;
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    vedlegg?: VedleggDto[];
};

export type UtenlandsoppholdsperiodeDto = {
    fom: string;
    tom: string;
    landkode: CountryCode;
    fomAfterTom?: boolean;
};

export type EttersendelseTilbakekrevingDto = {
    [key: string]: unknown;
};

export type AnnenInntektDto = {
    type: AnnenOpptjeningType;
    fom: string;
    tom?: string;
    land?: CountryCode;
    arbeidsgiverNavn?: string;
};

export type AnnenOpptjeningType =
    | 'ETTERLØNN_SLUTTPAKKE'
    | 'ETTERLØNN_ARBEIDSGIVER'
    | 'JOBB_I_UTLANDET'
    | 'LØNN_UNDER_UTDANNING'
    | 'MILITÆR_ELLER_SIVILTJENESTE'
    | 'SLUTTPAKKE'
    | 'VENTELØNN_VARTPENGER'
    | 'VENTELØNN'
    | 'VARTPENGER';

export type Dekningsgrad = '80' | '100';

export type ForeldrepengesøknadDto = {
    mottattdato?: string;
    søkerinfo: SøkerDto;
    rolle?: BrukerRolle;
    språkkode?: Målform;
    barn: BarnDto;
    frilans?: FrilansDto;
    egenNæring?: NæringDto;
    andreInntekterSiste10Mnd?: AnnenInntektDto[];
    annenForelder?: AnnenForelderDto;
    dekningsgrad: Dekningsgrad;
    uttaksplan: UttaksplanDto;
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    vedlegg?: VedleggDto[];
};

export type FrilansDto = {
    jobberFremdelesSomFrilans?: boolean;
    oppstart: string;
};

export type NæringDto = {
    fom: string;
    tom?: string;
    næringstype: Virksomhetstype;
    navnPåNæringen?: string;
    organisasjonsnummer?: string;
    næringsinntekt?: number;
    registrertINorge: boolean;
    registrertILand?: CountryCode;
    harBlittYrkesaktivILøpetAvDeTreSisteFerdigliknedeÅrene?: boolean;
    oppstartsdato?: string;
    hattVarigEndringAvNæringsinntektSiste4Kalenderår?: boolean;
    varigEndringDato?: string;
    varigEndringInntektEtterEndring?: number;
    varigEndringBeskrivelse?: string;
    varigEndringGyldig?: boolean;
};

export type Virksomhetstype = 'ANNEN' | 'JORDBRUK_SKOGBRUK' | 'FISKE' | 'DAGMAMMA';

export type AvtaltFerieDto = {
    arbeidsforhold: ArbeidsforholdDto;
    fom: string;
    tom: string;
    arbeidsforholdVirksomhet?: boolean;
};

export type BarnSvpDto = {
    termindato: string;
    fødselsdato?: string;
};

export type Del = TilretteleggingDto & {
    type: 'Del';
} & {
    fom: string;
    stillingsprosent: number;
};

export type Hel = TilretteleggingDto & {
    type: 'Hel';
} & {
    fom: string;
};

export type Ingen = TilretteleggingDto & {
    type: 'Ingen';
} & {
    fom: string;
};

export type SvangerskapspengesøknadDto = {
    mottattdato?: string;
    søkerinfo: SøkerDto;
    rolle?: BrukerRolle;
    språkkode: Målform;
    barn: BarnSvpDto;
    frilans?: FrilansDto;
    egenNæring?: NæringDto;
    andreInntekterSiste10Mnd?: AnnenInntektDto[];
    utenlandsopphold?: UtenlandsoppholdsperiodeDto[];
    tilretteleggingsbehov: TilretteleggingbehovDto[];
    avtaltFerie: AvtaltFerieDto[];
    vedlegg: VedleggDto[];
};

export type TilretteleggingDto = {
    type: string;
};

export type TilretteleggingbehovDto = {
    arbeidsforhold: ArbeidsforholdDto;
    behovForTilretteleggingFom: string;
    risikofaktorer?: string;
    tilretteleggingstiltak?: string;
    tilrettelegginger?: TilretteleggingDto[];
    risikofaktorerOgTilretteleggingtiltakSattForNæringFrilans?: boolean;
};

export type BrukerTekstDto = {
    dokumentType: DokumentType;
    tekst?: string;
    overskrift?: string;
};

export type DokumentType =
    | 'I000001'
    | 'I000002'
    | 'I000003'
    | 'I000004'
    | 'I000005'
    | 'I000006'
    | 'I000050'
    | 'I000027'
    | 'I500027'
    | 'I000114'
    | 'I000119'
    | 'I000067'
    | 'I000007'
    | 'I000023'
    | 'I000026'
    | 'I000032'
    | 'I000036'
    | 'I000037'
    | 'I000038'
    | 'I000039'
    | 'I000041'
    | 'I000042'
    | 'I000043'
    | 'I000044'
    | 'I000045'
    | 'I000047'
    | 'I000049'
    | 'I000051'
    | 'I000060'
    | 'I000061'
    | 'I000062'
    | 'I000063'
    | 'I000064'
    | 'I000065'
    | 'I000066'
    | 'I000107'
    | 'I000108'
    | 'I000109'
    | 'I000110'
    | 'I000111'
    | 'I000112'
    | 'I000116'
    | 'I000117'
    | 'I000118'
    | 'I000120'
    | 'I000121'
    | 'I000122'
    | 'I000123'
    | 'I000124'
    | 'I000130'
    | 'I000131'
    | 'I000132'
    | 'I000133'
    | 'I000140'
    | 'I000141'
    | 'I000143'
    | 'I000144'
    | 'I000145'
    | 'I000146'
    | 'I500001'
    | 'I500002'
    | 'I500003'
    | 'I500004'
    | 'I500005'
    | 'I500006'
    | 'I500050';

export type EttersendelseDto = {
    mottattdato?: string;
    type: YtelseType;
    saksnummer: string;
    brukerTekst?: BrukerTekstDto;
    vedlegg: VedleggDto[];
};

export type YtelseType = 'FORELDREPENGER' | 'SVANGERSKAPSPENGER' | 'ENGANGSSTØNAD';

export type YtelseMellomlagringType = 'FORELDREPENGER' | 'SVANGERSKAPSPENGER' | 'ENGANGSSTONAD';

export type FormDataContentDisposition = {
    type?: string;
    parameters?: {
        [key: string]: string;
    };
    fileName?: string;
    creationDate?: string;
    modificationDate?: string;
    readDate?: string;
    size?: number;
    name?: string;
};

export type ProsessTaskDataDto = {
    id: number;
    taskType: string;
    nesteKjøringEtter?: string;
    gruppe: string;
    sekvens: string;
    status: string;
    sistKjørt?: string;
    sisteFeilKode?: string;
    taskParametre?: {
        [key: string]: string;
    };
};

export type ProsessTaskOpprettInputDto = {
    taskType: string;
    taskParametre: {
        [key: string]: string;
    };
};

export type FeiletProsessTaskDataDto = {
    id: number;
    taskType: string;
    nesteKjøringEtter?: string;
    gruppe: string;
    sekvens: string;
    status: string;
    sistKjørt?: string;
    sisteFeilKode?: string;
    taskParametre?: {
        [key: string]: string;
    };
    sisteKjøringServerProsess?: string;
    sisteFeilTekst?: string;
    feiledeForsøk?: number;
};

export type IkkeFerdigProsessTaskStatusEnum = 'FEILET' | 'VENTER_SVAR' | 'SUSPENDERT' | 'VETO' | 'KLAR';

/**
 * Resultatet av asynkron-restart av en eksisterende prosesstask
 */
export type ProsessTaskRestartResultatDto = {
    prosessTaskId: number;
    /**
     * Nåværende status (KLAR)
     */
    prosessTaskStatus: string;
    /**
     * Kjøretidspunkt for restart av prosessen
     */
    nesteKjoeretidspunkt: string;
};

export type FeiletProsessTaskStatusEnum = 'FEILET' | 'VENTER_SVAR' | 'SUSPENDERT';

/**
 * Resultatet av asynkron-restart av feilede prosesstasks
 */
export type ProsessTaskRetryAllResultatDto = {
    /**
     * Prosesstasks som restartes
     */
    prosessTaskIds?: number[];
};

export type SokeFilterDto = {
    tekst: string;
    sisteKjoeretidspunktFraOgMed?: string;
    sisteKjoeretidspunktTilOgMed?: string;
};

export type SendData = {
    body: EndringssøknadForeldrepengerDto;
    path?: never;
    query?: never;
    url: '/api/soknad/foreldrepenger/endre';
};

export type SendResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type Send1Data = {
    body: EngangsstønadDto;
    path?: never;
    query?: never;
    url: '/api/soknad/engangsstonad';
};

export type Send1Responses = {
    /**
     * default response
     */
    default: unknown;
};

export type Send2Data = {
    body: EttersendelseTilbakekrevingDto;
    path?: never;
    query?: never;
    url: '/api/soknad/oppgave';
};

export type Send2Responses = {
    /**
     * default response
     */
    default: unknown;
};

export type Send3Data = {
    body: ForeldrepengesøknadDto;
    path?: never;
    query?: never;
    url: '/api/soknad/foreldrepenger';
};

export type Send3Responses = {
    /**
     * default response
     */
    default: unknown;
};

export type Send4Data = {
    body: SvangerskapspengesøknadDto;
    path?: never;
    query?: never;
    url: '/api/soknad/svangerskapspenger';
};

export type Send4Responses = {
    /**
     * default response
     */
    default: unknown;
};

export type Send5Data = {
    body: EttersendelseDto;
    path?: never;
    query?: never;
    url: '/api/soknad/ettersend';
};

export type Send5Responses = {
    /**
     * default response
     */
    default: unknown;
};

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/soknad/status';
};

export type StatusResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type FinnesDetAktivMellomlagringData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storage/aktive';
};

export type FinnesDetAktivMellomlagringResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type SlettMellomlagringData = {
    body?: never;
    path: {
        ytelse: YtelseMellomlagringType;
    };
    query?: never;
    url: '/api/storage/{ytelse}';
};

export type SlettMellomlagringResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type LesSøknadData = {
    body?: never;
    path: {
        ytelse: YtelseMellomlagringType;
    };
    query?: never;
    url: '/api/storage/{ytelse}';
};

export type LesSøknadResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type LagreSøknadYtelseData = {
    body?: string;
    path: {
        ytelse: YtelseMellomlagringType;
    };
    query?: never;
    url: '/api/storage/{ytelse}';
};

export type LagreSøknadYtelseResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type LagreVedleggData = {
    body?: {
        vedlegg?: FormDataContentDisposition;
    };
    path: {
        ytelse: YtelseMellomlagringType;
    };
    query?: {
        uuid?: string;
    };
    url: '/api/storage/{ytelse}/vedlegg';
};

export type LagreVedleggResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type SlettVedleggData = {
    body?: never;
    path: {
        ytelse: YtelseMellomlagringType;
        key: string;
    };
    query?: never;
    url: '/api/storage/{ytelse}/vedlegg/{key}';
};

export type SlettVedleggResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type LesVedleggData = {
    body?: never;
    path: {
        ytelse: YtelseMellomlagringType;
        key: string;
    };
    query?: never;
    url: '/api/storage/{ytelse}/vedlegg/{key}';
};

export type LesVedleggResponses = {
    /**
     * default response
     */
    default: Blob | File;
};

export type LesVedleggResponse = LesVedleggResponses[keyof LesVedleggResponses];

export type CreateProsessTaskData = {
    /**
     * Informasjon for restart en eksisterende prosesstask
     */
    body?: ProsessTaskOpprettInputDto;
    path?: never;
    query?: never;
    url: '/api/prosesstask/create';
};

export type CreateProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type CreateProsessTaskResponses = {
    /**
     * Prosesstaskens oppdatert informasjon
     */
    202: ProsessTaskDataDto;
};

export type CreateProsessTaskResponse = CreateProsessTaskResponses[keyof CreateProsessTaskResponses];

export type FinnFeiletProsessTaskData = {
    body?: never;
    path: {
        prosessTaskId: number;
    };
    query?: never;
    url: '/api/prosesstask/feil/{prosessTaskId}';
};

export type FinnFeiletProsessTaskErrors = {
    /**
     * Feil input
     */
    400: unknown;
    /**
     * Tom respons når angitt prosesstask-id ikke finnes
     */
    404: unknown;
};

export type FinnFeiletProsessTaskResponses = {
    /**
     * Angitt prosesstask-id finnes
     */
    200: FeiletProsessTaskDataDto;
};

export type FinnFeiletProsessTaskResponse = FinnFeiletProsessTaskResponses[keyof FinnFeiletProsessTaskResponses];

export type FinnProsessTasksData = {
    body?: never;
    path: {
        /**
         * Liste av statuser som skal hentes.
         */
        prosessTaskStatus: IkkeFerdigProsessTaskStatusEnum;
    };
    query?: never;
    url: '/api/prosesstask/list/{prosessTaskStatus}';
};

export type FinnProsessTasksResponses = {
    /**
     * Liste over prosesstasker, eller tom liste når angitt/default søkefilter ikke finner noen prosesstasker
     */
    200: ProsessTaskDataDto;
};

export type FinnProsessTasksResponse = FinnProsessTasksResponses[keyof FinnProsessTasksResponses];

export type RestartProsessTaskData = {
    body?: never;
    path: {
        prosessTaskId: number;
        prosessTaskStatus: FeiletProsessTaskStatusEnum;
    };
    query?: never;
    url: '/api/prosesstask/launch/{prosessTaskId}/{prosessTaskStatus}';
};

export type RestartProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type RestartProsessTaskResponses = {
    /**
     * Prosesstaskens oppdatert informasjon
     */
    200: ProsessTaskRestartResultatDto;
};

export type RestartProsessTaskResponse = RestartProsessTaskResponses[keyof RestartProsessTaskResponses];

export type RetryAllProsessTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/prosesstask/retryall';
};

export type RetryAllProsessTaskErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type RetryAllProsessTaskResponses = {
    /**
     * Response med liste av prosesstasks som restartes
     */
    200: ProsessTaskRetryAllResultatDto;
};

export type RetryAllProsessTaskResponse = RetryAllProsessTaskResponses[keyof RetryAllProsessTaskResponses];

export type SearchProsessTasksData = {
    /**
     * Søkefilter for å begrense resultatet av returnerte prosesstask.
     */
    body?: SokeFilterDto;
    path?: never;
    query?: never;
    url: '/api/prosesstask/search';
};

export type SearchProsessTasksResponses = {
    /**
     * Liste over prosesstasker, eller tom liste når angitt/default søkefilter ikke finner noen prosesstasker
     */
    200: ProsessTaskDataDto;
};

export type SearchProsessTasksResponse = SearchProsessTasksResponses[keyof SearchProsessTasksResponses];

export type SetFeiletProsessTaskFerdigData = {
    body?: never;
    path: {
        prosessTaskId: number;
        prosessTaskStatus: IkkeFerdigProsessTaskStatusEnum;
    };
    query?: never;
    url: '/api/prosesstask/setferdig/{prosessTaskId}/{prosessTaskStatus}';
};

export type SetFeiletProsessTaskFerdigErrors = {
    /**
     * Feilet pga ukjent feil eller tekniske/funksjonelle feil
     */
    500: unknown;
};

export type SetFeiletProsessTaskFerdigResponses = {
    /**
     * Angitt prosesstask-id satt til status FERDIG
     */
    200: unknown;
};
