export enum PeriodeResultatÅrsak {
    AVSLAG_FRATREKK_PLEIEPENGER = 'AVSLAG_FRATREKK_PLEIEPENGER',
    AVSLAG_UTSETTELSE_TILBAKE_I_TID = 'AVSLAG_UTSETTELSE_TILBAKE_I_TID',
    INNVILGET_UTTAK_AVSLÅTT_GRADERING_TILBAKE_I_TID = 'INNVILGET_UTTAK_AVSLÅTT_GRADERING_TILBAKE_I_TID',
    AVSLAG_HULL_MELLOM_FORELDRENES_PERIODER = 'AVSLAG_HULL_MELLOM_FORELDRENES_PERIODER',
    ANNET = 'ANNET',
}
