const MAKS_PERMISJONSLENGDE_I_ÅR = 3;
const MAKS_FERIEDAGER_ETT_ÅR = 21;
const MAKS_FERIEDAGER_MED_OVERFØRING = 52;
const ANTALL_UKER_MØDREKVOTE_ETTER_FØDSEL = 6;
const ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL = 3;
const MAKS_ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL = 12;
const ANTALL_UKER_FORELDREPENGER_BARE_FAR_HAR_RETT_100_PROSENT = 40;
const ANTALL_UKER_FORELDREPENGER_BARE_FAR_HAR_RETT_80_PROSENT = 50;
const ANTALL_UKER_2_BARN_100_PROSENT_UTTAK = 17;
const ANTALL_UKER_2_BARN_80_PROSENT_UTTAK = 21;
const ANTALL_UKER_3_ELLER_FLERE_BARN_100_PROSENT_UTTAK = 46;
const ANTALL_UKER_3_ELLER_FLERE_BARN_80_PROSENT_UTTAK = 56;

const uttaksConstants = {
    MAKS_PERMISJONSLENGDE_I_ÅR,
    MAKS_FERIEDAGER_ETT_ÅR,
    MAKS_FERIEDAGER_MED_OVERFØRING,
    ANTALL_UKER_MØDREKVOTE_ETTER_FØDSEL,
    ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL,
    MAKS_ANTALL_UKER_FORELDREPENGER_FØR_FØDSEL,
    ANTALL_UKER_FORELDREPENGER_BARE_FAR_HAR_RETT_100_PROSENT,
    ANTALL_UKER_FORELDREPENGER_BARE_FAR_HAR_RETT_80_PROSENT,
    ANTALL_UKER_2_BARN_100_PROSENT_UTTAK,
    ANTALL_UKER_2_BARN_80_PROSENT_UTTAK,
    ANTALL_UKER_3_ELLER_FLERE_BARN_100_PROSENT_UTTAK,
    ANTALL_UKER_3_ELLER_FLERE_BARN_80_PROSENT_UTTAK,
};

export default uttaksConstants;
