apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: foreldrepengesoknad-uttak-rework
    namespace: teamforeldrepenger
    labels:
        team: teamforeldrepenger
spec:
    accessPolicy:
        outbound:
            external:
                - host: dekoratoren.dev.nav.no
    image: { { image } }
    port: 8080
    replicas:
        min: 2
        max: 2
        disableAutoScaling: true
    liveness:
        path: /health/isAlive
        initialDelay: 60
    readiness:
        path: /health/isReady
        initialDelay: 60
    prometheus:
        enabled: false
        path: /internal/actuator/prometheus
    ingresses:
        - 'https://foreldrepengesoknad-rework.dev.nav.no'
    resources:
        limits:
            cpu: 500m
            memory: 512Mi
        requests:
            cpu: 200m
            memory: 256Mi
    env:
        - name: APPRES_CMS_URL
          value: 'https://dekoratoren.dev.nav.no'
        - name: FORELDREPENGESOKNAD_API_URL
          value: 'https://foreldrepengesoknad-api.dev.nav.no/rest'
        - name: LOGINSERVICE_URL
          value: 'https://loginservice-testing.dev.nav.no/login'
        - name: FP_UTTAK_SERVICE_URL
          value: 'https://foreldrepengesoknad-api.dev.nav.no'
        - name: FEATURE_VIS_PERIODER_SOM_SENDES_INN
          value: 'on'
        - name: FEATURE_TEST_WLB_REGLER
          value: 'on'
        - name: FEATURE_TEST_WLB_REGLER
      value: "on"
    - name: FAMILIE
          value: 'https://familie.dev.nav.no'
        - name: APP_VERSION
          value: { { image } }
