apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  accessPolicy:
    outbound:
      external:
        - host: {{dekoratoren}}
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      disableAutoScaling: true
  liveness:
      path: /health/isAlive
      initialDelay: 10
  readiness:
      path: /health/isReady
      initialDelay: 10
  prometheus:
      enabled: false
      path: /internal/actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
   - name: APP_VERSION
     value: {{image}}
