apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: svangerskapspengesoknad-rework
    namespace: teamforeldrepenger
    labels:
        team: teamforeldrepenger
spec:
    accessPolicy:
        outbound:
            external:
                - host: dekoratoren.ekstern.dev.nav.no
    image: {{image}}
    port: 8080
    replicas:
        min: 2
        max: 2
        disableAutoScaling: true
    liveness:
        path: /health/isAlive
        initialDelay: 60
    readiness:
        path: /health/isReady
        initialDelay: 60
    prometheus:
        enabled: false
        path: /internal/actuator/prometheus
    ingresses:
        - 'https://svangerskapspengesoknad-rework.intern.dev.nav.no'
    resources:
        limits:
            cpu: 500m
            memory: 512Mi
        requests:
            cpu: 200m
            memory: 256Mi
    env:
        - name: APPRES_CMS_URL
          value: 'https://dekoratoren.ekstern.dev.nav.no'
        - name: FORELDREPENGESOKNAD_API_URL
          value: 'https://foreldrepengesoknad-api.intern.dev.nav.no/rest'
        - name: LOGINSERVICE_URL
          value: 'https://login.ekstern.dev.nav.no/oauth2/login'
        - name: LOG_VALIDATION
          value: 'false'
        - name: INNSYN
          value: 'https://foreldrepenger.intern.dev.nav.no'        
        - name: INNSYN_SAK
          value: 'https://foreldrepenger.intern.dev.nav.no/sak/'
          
