apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: foreldrepengesoknad-uttak-rework
    namespace: teamforeldrepenger
    labels:
        team: teamforeldrepenger
spec:
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      disableAutoScaling: true
  liveness:
      path: /health/isAlive
      initialDelay: 60
  readiness:
      path: /health/isReady
      initialDelay: 60
  prometheus:
      enabled: false
      path: /internal/actuator/prometheus
  ingresses:
    - "https://foreldrepengesoknad-rework.intern.dev.nav.no"
    - "https://foreldrepengesoknad-rework.dev.nav.no"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: APPRES_CMS_URL
      value: "https://dekoratoren.intern.dev.nav.no"
    - name: REST_API_URL
      value: "https://foreldrepengesoknad-api.intern.dev.nav.no/rest"
    - name: LOGIN_URL
      value: "https://loginservice-testing.dev.nav.no/login"
    - name: FEATURE_BRUK_SAKER_V2
      value: "off"
    - name: APP_VERSION
      value: {{image}}
