name: Bygg og deploy Engangsstønad
on:
  workflow_dispatch:
  push:
    branches:
      - 'felles_server_decorator'
    paths:
      - 'apps/engangsstonad/**'
      - 'packages/**'
      - '.deploy/engangsstonad/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-engangsstønad.yml'

env:
  APP: engangsstonad

jobs:
  build-app:
    name: Build
    permissions:
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-monorepo.yml@main
    with:
      build-image: ${{ github.ref_name == 'felles_server_decorator' }} # default: true
      push-image: ${{ github.ref_name == 'felles_server_decorator' }} # default: false
      app: ${{ env.APP }}
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'felles_server_decorator'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      app: /${{ env.APP }}
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      app: /${{ env.APP }}
    secrets: inherit
