name: Bygg og deploy Engangsstønad
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/engangsstonad/**'
      - 'packages/**'
      - 'server/**'
      - '.deploy/engangsstonad/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-engangsstonad.yml'
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - 'pnpm-lock.yaml'

jobs:
  build-app:
    name: Build
    permissions:
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-docker-bake.yml@main
    with:
      runs-on: 'ubuntu-latest-4-cores' # default: ubuntu-latest
      push-image: ${{ github.ref_name == 'master' }} # default: false
      bake-target: 'engangsstonad'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  upload-to-CDN:
    name: Upload assets to CDN
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    needs: build-app
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Login GAR
        uses: nais/login@v0
        id: login
        with:
          team: teamforeldrepenger
      - name: Extract dist from built image
        env:
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}/engangsstonad:${{ needs.build-app.outputs.build-version }}
        run: |
          docker pull "$IMAGE"
          cid=$(docker create "$IMAGE")
          docker cp "$cid:/app/public" ./cdn-dist
          docker rm "$cid"
      - name: Upload static files to CDN
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamforeldrepenger
          source: ./cdn-dist
          source_keep_parent_name: false
          destination: /engangsstonad/dist
      - run: 'echo "uploaded file ${{ steps.upload.outputs.uploaded }}"'

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/engangsstonad'
      deploy_context: '/engangsstonad'

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      image_suffix: '/engangsstonad'
      deploy_context: '/engangsstonad'
