name: Bygg og deploy Veiviser-fp-eller-es
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/veiviser-fp-eller-es/**'
      - 'packages/**'
      - 'server-uinnlogget/**'
      - '.deploy/veiviser-fp-eller-es/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-veiviser-fp-eller-es.yml'
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - 'pnpm-lock.yaml'

jobs:
  build-app:
    name: Build
    permissions:
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-docker-bake.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      runs-on: 'ubuntu-latest-4-cores' # default: ubuntu-latest
      push-image: ${{ github.ref_name == 'master' }} # default: false
      bake-target: 'veiviser-fp-eller-es'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/veiviser-fp-eller-es'
      deploy_context: '/veiviser-fp-eller-es'

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      image_suffix: '/veiviser-fp-eller-es'
      deploy_context: '/veiviser-fp-eller-es'
