name: Bygg og deploy Foreldrepengerplanlegger
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/planlegger/**'
      - 'packages/**'
      - 'server-uinnlogget/**'
      - '.deploy/planlegger/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-planlegger.yml'
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - 'pnpm-lock.yaml'

jobs:
  build-app:
    name: Build
    permissions:
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-docker-bake.yml@d4e74b74e16b16d1a9973225f33bb8d34e80943f
    with:
      runs-on: 'ubuntu-latest-4-cores' # default: ubuntu-latest
      push-image: ${{ github.ref_name == 'master' }} # default: false
      bake-target: 'planlegger'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d4e74b74e16b16d1a9973225f33bb8d34e80943f
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/planlegger'
      deploy_context: '/planlegger'

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d4e74b74e16b16d1a9973225f33bb8d34e80943f
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      image_suffix: '/planlegger'
      deploy_context: '/planlegger'
