name: Bygg og deploy Veiviser-hva-skjer-nar
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/veiviser-hva-skjer-nar/**'
      - 'packages/**'
      - 'server-uinnlogget/**'
      - '.deploy/veiviser-hva-skjer-nar/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-veiviser-hva-skjer-nar.yml'
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'apps/veiviser-hva-skjer-nar/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'

jobs:
  build-app:
    name: Build
    permissions:
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-docker-bake.yml@main
    with:
      runs-on: 'ubuntu-latest-4-cores' # default: ubuntu-latest
      push-image: ${{ github.ref_name == 'master' }} # default: false
      bake-target: 'veiviser-hva-skjer-nar'
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/veiviser-hva-skjer-nar'
      deploy_context: '/veiviser-hva-skjer-nar'
    secrets: inherit
