name: 'Deploy storybook'

on:
  push:
    branches: ['master']
    paths-ignore:
      - 'server/**'
      - 'server-uinnlogget/**'
  workflow_dispatch:

jobs:
  deploy-storybook:
    name: Deploy storybook pnpm
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - uses: navikt/fp-gha-workflows/.github/actions/setup-npmrc@main # ratchet:exclude
        with:
          npmAuthToken: ${{ secrets.READER_TOKEN }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # ratchet:pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v7.0.0
        with:
          node-version: '26'
          cache: pnpm

      - name: Cache turbo build setup
        id: hent-cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # ratchet:actions/cache/restore@v6.1.0
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Installer avhengigheter med Pnpm
        run: pnpm install --frozen-lockfile

      - name: Bygg Storybook med Pnpm
        run: pnpm build:storybook

      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # ratchet:actions/configure-pages@v6.0.0

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # ratchet:actions/upload-pages-artifact@v5.0.0
        with:
          path: ./.storybook-static-build
          overwrite: true

      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # ratchet:actions/deploy-pages@v5.0.0
        id: deployment

      - name: Lagre turbo cache
        if: always() && steps.hent-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # ratchet:actions/cache/save@v6.1.0
        with:
          key: ${{ steps.hent-cache.outputs.cache-primary-key }}
          path: .turbo
